src/Entity/Boutique.php
<?php

namespace App\Entity;

use App\Entity\Traits\Timestampable;
use App\Repository\BoutiqueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Serializable;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: BoutiqueRepository::class)]
#[ORM\HasLifecycleCallbacks]
/**
 * @Vich\Uploadable
 */
class Boutique implements Serializable
{ 
    use Timestampable;

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 150)]
    #[Assert\NotBlank(message: 'Vous devez remplir ce champ')]
    #[Assert\Length(min: 3, minMessage: "minimum 3 caractères")] 
    private $title;

    #[ORM\Column(type: 'text', nullable: true)]
    #[Assert\Length(min: 10, minMessage: "minimum 3 caractères")] 
    private $description;

    #[ORM\Column(type: 'string', length: 150, unique: true)]
    #[Assert\NotBlank(message: 'Vous devez remplir ce champ')]
    #[Assert\Length(exactly: 14, exactMessage: "Le SIRET doit faire 14 charactères")] 
    private $SIRET;

    #[ORM\Column(type: 'string', length: 150)]
    #[Assert\NotBlank(message: 'Vous devez remplir ce champ')]
    #[Assert\Length(min: 5, minMessage: "minimum 5 caractères")] 
    private $adresse;

    #[ORM\Column(type: 'integer')]
    #[Assert\NotBlank(message: 'Vous devez remplir ce champ')]
    #[Assert\Length(exactly: 5, exactMessage: 'Le code postal doit avoir 5 chiffres')] 
    private $code_postal;

    #[ORM\Column(type: 'string', length: 150)]
    #[Assert\NotBlank(message: 'Vous devez remplir ce champ')]
    #[Assert\Length(min: 3, minMessage: "minimum 3 caractères")]  
    private $ville;

    #[ORM\Column(type: 'string', length: 150, nullable: true)]
    #[Assert\Length(min: 10, minMessage: "minimum 10 caractères")] 
    private $tel;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="boutique_image", fileNameProperty="image")
     * @Assert\Image(maxSize="2M")
     * @Assert\NotNull(message="il faut choisir une image")
     * 
     * @var File|null
     */
    private  $imageFileBoutique;

    #[ORM\Column(type: 'string', length: 255)]    
    private $image;

     /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="logo_image", fileNameProperty="logo")
     * @Assert\Image(maxSize="2M")
     * @Assert\NotNull(message="il faut choisir une image")
     *
     * @var File|null
     */    
    private $imageFileLogo;

    #[ORM\Column(type: 'string', length: 255)]    
    private $logo;

    #[ORM\Column(type: 'boolean')]
    private $is_siret_verified = true;

    #[ORM\Column(type: 'boolean')]
    private $is_active = true;

    #[ORM\OneToOne(inversedBy: 'boutique', targetEntity: User::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\OneToMany(mappedBy: 'boutique', targetEntity: Produits::class, orphanRemoval: true)]
    private $produits;

    #[ORM\ManyToMany(targetEntity: Categorie::class, inversedBy: 'boutiques')]
    private $categorie;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
        $this->categorie = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSIRET(): ?string
    {
        return $this->SIRET;
    }

    public function setSIRET(?string $SIRET): self
    {
        $this->SIRET = $SIRET;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(?int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }

    /**     
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFileBoutique
     */
    public function setImageFileBoutique(?File $imageFileBoutique = null): void
    {
        $this->imageFileBoutique = $imageFileBoutique;

        if (null !== $imageFileBoutique) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->setModifiedAt(new \DateTimeImmutable);
        }
    }

    public function getImageFileBoutique(): ?File
    {
        return $this->imageFileBoutique;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**     
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFileLogo
     */
    public function setImageFileLogo(?File $imageFileLogo = null): void
    {
        $this->imageFileLogo = $imageFileLogo;

        if (null !== $imageFileLogo) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->setModifiedAt(new \DateTimeImmutable);
        }
    }

    public function getImageFileLogo(): ?File
    {
        return $this->imageFileLogo;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(?string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function isIsSiretVerified(): ?bool
    {
        return $this->is_siret_verified;
    }

    public function setIsSiretVerified(?bool $is_siret_verified): self
    {
        $this->is_siret_verified = $is_siret_verified;

        return $this;
    }

    public function isIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(?bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }  

    public function serialize()
    {
        $this->image = base64_encode($this->image);
        $this->logo = base64_encode($this->logo);
    }

    public function unserialize($serialized)
    {
        $this->image = base64_decode($this->image);
        $this->logo = base64_decode($this->logo);

    }

    /**
     * @return Collection<int, produits>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(produits $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->setBoutique($this);
        }

        return $this;
    }

    public function removeProduit(produits $produit): self
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getBoutique() === $this) {
                $produit->setBoutique(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Categorie>
     */
    public function getCategorie(): Collection
    {
        return $this->categorie;
    }

    public function addCategorie(Categorie $categorie): self
    {
        if (!$this->categorie->contains($categorie)) {
            $this->categorie[] = $categorie;
        }

        return $this;
    }

    public function removeCategorie(Categorie $categorie): self
    {
        $this->categorie->removeElement($categorie);

        return $this;
    }

}

templates/home/home_partials/_banniere.html.twig
<section class="banniere-des-marques">
    <div class="banniere">
        <h2 class="heading-secondary text-center u-margin-top-small u-margin-bottom-medium">Ils nous font confiance</h2>
        <ul class="boxs">
            {% for boutique in boutiques %}
                <li>
                    <img src="{{ vich_uploader_asset(boutique, 'imageFileLogo') }}" alt="{{ boutique.title }}" alt="">
                </li>                
            {% endfor %}           
        </ul>
    </div>    
</section>

templates/home/home_partials/_bon_plans.html.twig
<section id="home_plan">
    <div class="u-center-text u-margin-bottom-big">
        <h2 class="heading-secondary">
            Les bon plans
        </h2>
    </div>


    <div class="lesbonsplans">
        <div class="wrap2">
            {% for prodBonPlan in prodBonPlans %}
                {# {% if prodBonPlan.boutique.isActive %}   #}
                    <div class="mini_plan">
                        <div class="plan_img">
                            <a href="{{path('app_single_produit', {id: prodBonPlan.id})}}"><img src="{{vich_uploader_asset(prodBonPlan, 'imageFileProduit')}}"></a>
                        </div>
                        <div class="plan_text">
                            <h2>{{ prodBonPlan.title }}</h2>
                        </div>
                    </div>
                {# {% endif %} #}
            {% endfor %}
        </div>
        <div class="d-flex justify-content-center">
                {% do prodBonPlans.setPageRange(2) %}
                {{ knp_pagination_render(prodBonPlans, 'layouts/base_partials/pagination.html.twig') }}
        </div>
    </div>


    <div class="btn__ccm u-margin-top-medium u-margin-bottom-huge">{# bouton pour Voir les bons plans #} 
        <a href="{{path('app_produit_bonplans')}}" class="ccm btn-front btn-front--green">Les Bons Plans</a>
    </div>
</section>

templates/home/home_partials/_comment_ca_marche.html.twig
<!-- Comment ca marche -->        
<section class="section-commentCaMarche u-margin-top-huge">    
    <div class="u-center-text u-margin-bottom-medium">
        <h2 class="heading-secondary">
            Comment ça marche?
        </h2>
    </div>

    <div class="grid grid--4-cols  u-margin-bottom-medium">
        <!-- card 1 -->
        <div class="card">
            <div class="card__side card__side--front">
                <div class="card__picture card__picture--1">
                    &nbsp;
                </div>
                <h4 class="card__heading">
                    <span class="card__heading-span card__heading-span--1">Etape 1</span>                                    
                </h4>            
            </div>
            <!-- Back side comment ca marche -->
            <div class="card__side card__side--back card__side--back-1">
                <div class="card__cta">
                    <div class="card__text-box">
                        <p class="card__description">Inscrivez-vous... <br> Si vous êtes utilisateur, validez votre inscription et faites vos premiers achats ou profitez des services proposés. </p>                                

                    </div>                    

                </div>
            </div>
        </div>
        <!-- card 2 -->
        <div class="card">
            <div class="card__side card__side--front">
                <div class="card__picture card__picture--2">
                    &nbsp;
                </div>
                <h4 class="card__heading">
                    <span class="card__heading-span card__heading-span--1">Etape 2</span>                                    
                </h4>
                
            </div>                    
            <div class="card__side card__side--back card__side--back-2">
                <div class="card__cta">
                    <div class="card__text-box">
                        <p class="card__description">Vous êtes commerçant ? <br> Cochez la case et vous serez redirigé vers le formulaire de création de boutique.</p>                                
                    </div>                    
                </div>
            </div>
        </div>
        <!-- card 3 -->
        <div class="card">
            <div class="card__side card__side--front">
                <div class="card__picture card__picture--3">
                    &nbsp;
                </div>
                <h4 class="card__heading">
                    <span class="card__heading-span card__heading-span--1">Etape 3</span>                                    
                </h4>
               
            </div>
            <div class="card__side card__side--back card__side--back-1">
                <div class="card__cta">
                    <div class="card__text-box">
                        <p class="card__description">Le formulaire est validé... <br> Vous aurez accès à votre page de gestion de boutique, selon votre catégorie vous aurez accès à un service spécifique lié à votre activité. </p>                                
                    </div>
                    
                </div>
            </div>
        </div>
        <!-- card 4 -->
        <div class="card">
            <div class="card__side card__side--front">
                <div class="card__picture card__picture--4">
                    &nbsp;
                </div>
                <h4 class="card__heading">
                    <span class="card__heading-span card__heading-span--1">Etape 4</span>                                    
                </h4>
                
            </div>
            <div class="card__side card__side--back card__side--back-1">
                <div class="card__cta">
                    <div class="card__text-box">
                        <p class="card__description">Gérez votre boutique... <br> Créez des produits, sélectionnez des bon plans(mis en avant sur le site), ils seront automatiquement inséré en ligne, ils sortiront de la boutique si le stock s'épuise.</p>                                
                    </div>
                   
                </div>
            </div>
        </div>
        <!-- fin des 4 cards -->

    </div>  <!-- Grid end -->

    <div class="btn__ccm u-margin-top-medium u-margin-bottom-huge">{# bouton pour s'inscrire #} 
        {% if app.user %}
            <a href="{{path('app_index_boutiques')}}" class="ccm btn-front btn-front--green">Voir les boutiques</a>
            
        {% else %}
            <a href="{{path('app_register')}}" class="ccm btn-front btn-front--green">Inscrivez-vous maintenant!</a>
        {% endif %}    
    </div>

</section>

templates/home/home_partials/_hero.html.twig
<section id="intro">
    <div class="wrap1">        
        <div class="introduction">
            <div class="titre">
                <h1 class="heading-primary heading-primary--main">Proxi'Services<br> Pont-audemer</h1>                
            </div>
            <div class="text">
                <p>Proxi'Service est un site de ventes et de services regroupant les commerçants d'une communauté de commune. Son principe est de permettre aux petits commerçants d'avoir une fenêtre sur internet. Les options proposés seront adaptés à chaque type de commerce dans le but d'optimiser l'activité local et d'améliorer les services apportés aux clients.</p>
            </div>
            {% if app.user %}
            {% if is_granted('ROLE_COMMERCANT') %}
                <div class='gestion_com'>
                    <ul>
                    {% if app.user.boutique %}
                        <li><a class="admin_com_link" href="{{path('app_commercant_default')}}">Gestion commercant</a></li>
                    {% else %}                                                
                        <li><a class="admin_com_link" href="{{path('app_create_boutique')}}">Créer ma boutique</a></li>
                    {% endif %}

                    {% if is_granted('ROLE_ADMIN') %}
                    <li><a class="admin_com_link" href="{{path('app_admin_default')}}">Gestion admin</a></li>
                    {% endif %}                    
                    </ul>        
                </div>
            {% endif %}
        {% endif %}
        </div>        
    </div>  
        
</section>